controller_manager:
  ros__parameters:
    update_rate: 50

    control_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

control_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["Revolute_2"]
    right_wheel_names: ["Revolute_1"]

    wheel_separation: 0.2
    wheel_radius: 0.05

    base_frame_id: base_link

    publish_rate: 50.0

    enable_odom_tf: true
    odom_frame_id: odom
  
    publish_cmd: true

    cmd_vel_timeout: 0.25

    use_stamped_vel: false

    update_rate: 50
